apiVersion: v1
appVersion: 1.0.461
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/go.png
name: go-demo-6
version: 1.0.461
